#TODO: replace example strings with text scraped from URLs --> use requests and BeautifulSoup? or API?
#TODO: research how to integrate into database --> store topics for each text?
#TODO: research if there are better models than LDA to achieve this?

import os
import nltk
import re
import string
import gensim
import numpy as np
from nltk.corpus import stopwords
from gutenbergpy import textget
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from gensim import corpora
from gensim.models import LdaModel
from gensim.models.coherencemodel import CoherenceModel
import pyLDAvis
import pyLDAvis.gensim_models as gensimvisualize

nltk.download("punkt")
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download("punkt_tab")
nltk.download("averaged_perceptron_tagger_eng")

# load WordNet POS tags for lemmatization
def wordnet_pos_tags(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def txt_preprocess_pipeline(text):
    working_txt = text
    main_txt = textget.strip_headers(working_txt.encode('utf-8')).decode('utf-8')
    main_txt = re.sub(r'end of the project gutenberg', '', main_txt, flags=re.IGNORECASE)
    standard_txt = main_txt.lower()
    clean_txt = re.sub(r'\n', ' ', standard_txt)
    clean_txt = re.sub(r'\s+', ' ', clean_txt)
    clean_txt = clean_txt.strip()
    tokens = word_tokenize(clean_txt)
    filtered_tokens_alpha = [word for word in tokens if word.isalpha() and not re.match(r'\d+', word)]
    stop_words = set(stopwords.words('english'))
    filtered_tokens_stopwords = [word for word in filtered_tokens_alpha if word not in stop_words]
    lemmatizer = WordNetLemmatizer()
    pos_tags = nltk.pos_tag(filtered_tokens_stopwords)
    lemmatized_tokens = [lemmatizer.lemmatize(word, wordnet_pos_tags(tag)) for word, tag in pos_tags]
    return lemmatized_tokens

texts_platypus_example = """
The only egg-laying mammals are the monotremes, which include the platypus and echidnas of Australia and New Guinea.
These animals lay eggs that hatch outside the mother's body. After hatching, the young are nourished with milk produced by mammary glands.
There are many interesting facts about platypi. For example, they have a bill similar to that of a duck, webbed feet, and a tail like a beaver.
Echidnas, also known as spiny anteaters, have spines similar to those of a porcupine and a long, sticky tongue used for catching ants and termites.
Monotremes are unique among mammals in that they possess a cloaca, a single opening for excretion and reproduction.
Both platypi and echidnas are found in Australia, with the platypus inhabiting freshwater rivers and lakes, while echidnas are more terrestrial and can be found in a variety of habitats including forests and deserts.
Monotremes are an ancient lineage of mammals, with fossil evidence suggesting they have existed for over 100 million years.
Despite their unusual characteristics, monotremes share many features with other mammals, such as warm-bloodedness, fur, and the production of milk for their young.
Monotremes are also known for their electroreception abilities, which allow them to detect electric fields generated by the muscle contractions of their prey.
This adaptation is particularly useful for the platypus, which hunts underwater with its eyes, ears, and nostrils closed.
"""
# top 3 output!!!: mammal monotreme platypus

texts_pittsburgh_example = """
Pittsburgh is a city in western Pennsylvania, United States, known for its rich history in steel production and its vibrant cultural scene.
Situated at the confluence of the Allegheny, Monongahela, and Ohio Rivers, Pittsburgh has earned the nickname "The Steel City" due to its pivotal role in the American steel industry during the late 19th and early 20th centuries.
The city is also known for its several professional sports teams, including the Pittsburgh Steelers (NFL), Pittsburgh Penguins (NHL), and Pittsburgh Pirates (MLB), which have a passionate fan base.
Pittsburgh is home to numerous universities and colleges, including the University of Pittsburgh and Carnegie Mellon University, both of which are renowned for their research programs and contributions to technology and innovation.
The city's cultural offerings include a variety of museums, theaters, and music venues, such as the Andy Warhol Museum, the Carnegie Museum of Art, and the Pittsburgh Symphony Orchestra.
Pittsburgh has undergone significant revitalization in recent decades, transitioning from its industrial roots to a more diversified economy that includes healthcare, education, and technology sectors.
The city's skyline is marked by its iconic bridges and modern architecture, with landmarks such as the PPG Place and the Duquesne Incline offering stunning views of the cityscape.
Pittsburgh's neighborhoods each have their own unique character and charm, from the historic Strip District to the trendy Lawrenceville area.
The city also boasts a strong culinary scene, with a variety of restaurants offering everything from traditional Pennsylvania Dutch cuisine to innovative farm-to-table dining experiences.
"""
# top 3 output!!!: pittsburgh city include

texts_computer_science_example = """
Computer science is the study of computers and computational systems. It encompasses a wide range of topics, including algorithms, data structures, programming languages, software development, and computer architecture.
Computer scientists work on designing and analyzing algorithms to solve complex problems efficiently. They also develop software applications, operating systems, and network protocols that enable computers to communicate and function effectively.
The field of computer science is constantly evolving, with new technologies and methodologies emerging regularly. Areas such as artificial intelligence, machine learning, and cybersecurity are at the forefront of current research and development.
Computer science also plays a crucial role in various industries, including healthcare, finance, entertainment, and transportation. It enables advancements in data analysis, simulation, and automation, leading to improved services and products.
Education in computer science typically involves learning programming languages, software engineering principles, and theoretical concepts such as computational complexity and automata theory.
Many universities and institutions offer specialized programs and degrees in computer science, preparing students for careers in academia, industry, and research.
The impact of computer science on society is profound, influencing how we communicate, work, and live our daily lives. As technology continues to advance, the importance of computer science will only grow, shaping the future in unprecedented ways.
"""
# top 3 output!!!: computer science program

# load dictionary
# dictionary = corpora.Dictionary()

# generate corpus as BoW
# corpus = [dictionary.doc2bow(text) for text in texts]
# corpus = []
processed_text = txt_preprocess_pipeline(texts_computer_science_example)
dictionary = corpora.Dictionary([processed_text])
# dictionary.filter_extremes(no_below=2)
corpus = [dictionary.doc2bow(processed_text)]

# train LDA model
lda_model = LdaModel(
    corpus=corpus,
    id2word=dictionary,
    num_topics=3,
    random_state=13,
    passes=10
)
# print LDA topics
# for idx, topic in lda_model.print_topics(-1):
#     print(f"Topic {idx}: {topic}")

# only print the words in each topic
# for idx, topic in lda_model.print_topics(-1):
#     topic_words = re.findall(r'\"(.*?)\"', topic)
#     print(f"THE TOPIC IS {' '.join(topic_words)}")

# only print the first three words in the first topic
for idx, topic in lda_model.print_topics(-1):
    if idx == 0:
        topic_words = re.findall(r'\"(.*?)\"', topic)
        print(f"THE TOPIC IS {' '.join(topic_words[:3])}")

# for idx, topic in lda_model.print_topics(-1):
#     print(f"THE TOPIC IS {topic}")

# compute coherence score
# coherence_model_lda = CoherenceModel(model=lda_model, texts=[processed_text], dictionary=dictionary, coherence='c_v')